name: Get PR Number
description: "Get PR Number"

inputs:
  branch_name:
    description: "Branch Name"
    required: true
  pr_array:
    description: "List of PRs"
    required: true

runs:
  using: composite

  # Set the steps
  steps:
    - id: pr-num
      shell: bash
      env:
        BRANCH: ${{ inputs.branch_name }}
        PR_ARRAY: ${{ inputs.pr_array }}
      run: |
        echo "pr_number=$(node get_pr_number.js)" >> $GITHUB_ENV
      working-directory: "${{ github.action_path }}"
