name: Get PR List Length
description: "Get PR List Length"

runs:
  using: composite

  # Set the steps
  steps:
    - id: pr-list-len
      shell: bash
      run: |
        echo "pr_list_length<<EOF" >> $GITHUB_ENV
        echo "$(node get_length.js)" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      working-directory: "${{ github.action_path }}"
