name: Get PR List Length
description: "Get PR List Length"

inputs:
  pr_array:
    description: "List of PRs"
    required: true

runs:
  using: composite

  # Set the steps
  steps:
    - id: pr-list-len
      shell: bash
      env:
        PR_ARRAY: ${{ inputs.pr_array }}
      run: |
        echo "pr_list_length=$(node get_length.js)" >> $GITHUB_ENV
      working-directory: "${{ github.action_path }}"
