name: PR TEST - Technical Review
on:
  repository_dispatch:
    types: prtestautomation

run-name: PR TEST - ${{ toJSON(github.event.client_payload.ritm_details.number) }}

#Special Pemissions required for OIDC authentication
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  branch_check_and_create:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: ${{toJSON(github.event.client_payload)}}
      TASK_ID: ${{toJSON(github.event.client_payload.task_details.sysid)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup Git Configuration
        id: setupgit
        run: |
          git config --global user.name aqueefcs
          git config --global user.email aqueefalimansari007@gmail.com

      - name: Check if branch exists
        id: check_branch
        run: |
          BRANCH_NAME="${{ toJSON(github.event.client_payload.ritm_details.number) }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

          if git ls-remote --exit-code --heads origin $BRANCH_NAME > /dev/null 2>&1; then
            echo "Branch exist"
            EXIT_CODE="true"
            echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT
          else
            echo "Branch not exist"
            EXIT_CODE="false"
            echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT
          fi

      - name: Create Branch
        if: steps.check_branch.outputs.exitcode == 'false'
        run: |
          echo ${{steps.check_branch.outputs.branch_name}}
          git remote set-url origin "https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ github.repository }}"
          git push origin HEAD:refs/heads/${{ steps.check_branch.outputs.branch_name }}
          echo "Branch ${{ steps.check_branch.outputs.branch_name }} created"

    outputs:
      exit-code: ${{ steps.check_branch.outputs.exitcode }}
      branch-name: ${{ steps.check_branch.outputs.branch_name }}

  azureProvision:
    needs: ["branch_check_and_create"]
    runs-on: ubuntu-latest
    env:
      PAYLOAD: ${{toJSON(github.event.client_payload)}}
      TASK_ID: ${{toJSON(github.event.client_payload.task_details.sysid)}}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.branch_check_and_create.outputs.branch-name }}

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

        # Running Nodejs code to generate terraform files for azure resources
      - name: Run Nodejs Script
        run: |
          cd ./Code-Generation
          npm install
          node index.js

      - name: Setup Git Configuration
        id: setupgit
        run: |
          git config --global user.name aqueefcs
          git config --global user.email aqueefalimansari007@gmail.com

      - name: Check Diff
        id: diff
        run: |
          echo "has_changes=$(git diff --quiet || echo 'true')" >> $GITHUB_OUTPUT

      - name: Check diff output
        run: |
          echo ${{ steps.diff.outputs.has_changes }}

      - name: Push to Branch
        if: steps.diff.outputs.has_changes == 'true'
        run: |
          echo ${{ needs.branch_check_and_create.outputs.branch-name }}
          git remote set-url origin "https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ github.repository }}"
          git add .
          git commit -m "pr-test-automation"
          git push origin HEAD:refs/heads/${{ needs.branch_check_and_create.outputs.branch-name }}
          echo "Pushed to Branch ${{ needs.branch_check_and_create.outputs.branch-name }}"

      - name: Check for PR
        id: check_pr
        run: |
          echo "pr_exist=$(gh api "repos/${{ github.repository }}/pulls")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Get Pr List Length
        id: pr-length
        if: steps.check_pr.outcome == 'success'
        uses: ./Code-Generation/actions/get-pr-list-length
        with:
          pr_array: ${{ steps.check_pr.outputs.pr_exist }}

      - name: set pr length output
        id: set-pr-len
        run: |
          prlen="${{ env.pr_list_length }}"
          echo "PRLEN=$prlen" >> $GITHUB_OUTPUT

      - name: print PR len before
        run: echo ${{ steps.set-pr-len.outputs.PRLEN }}

      - name: Check if Any PR for Checkout Branch
        id: pr_num
        if: steps.set-pr-len.outputs.PRLEN  == 'true'
        uses: ./Code-Generation/actions/get-pr-number
        with:
          branch_name: ${{ needs.branch_check_and_create.outputs.branch-name }}
          pr_array: ${{ steps.check_pr.outputs.pr_exist }}

      - name: set pr num output
        id: set-pr-num
        run: |
          prnumoutput="${{ env.pr_number }}"
          echo "PRNUMOUTPUT=$prnumoutput" >> $GITHUB_OUTPUT

      - name: print PR before
        run: echo ${{ steps.set-pr-num.outputs.PRNUMOUTPUT }}

      - name: Create Pull Request
        id: create_pr
        if: steps.set-pr-len.outputs.PRLEN == '0' || steps.set-pr-num.outputs.PRNUMOUTPUT == 'false'
        run: |
          if ${{ steps.diff.outputs.has_changes }} == 'true'; then
               gh pr create --title "${{ needs.branch_check_and_create.outputs.branch-name }} PR Test" --body "PR TEST - Update Comment in PR" --base "main" --head "${{ needs.branch_check_and_create.outputs.branch-name }}"
          else
               echo "No commits between main and ${{ needs.branch_check_and_create.outputs.branch-name }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Check after PR
        id: after-pr-check
        run: |
          echo "after_pr_exist=$(gh api "repos/${{ github.repository }}/pulls")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: get PR num after PR
        id: get_pr_num
        if: steps.after-pr-check.outcome == 'success'
        uses: ./Code-Generation/actions/get-after-pr-number
        with:
          branch_name: ${{ needs.branch_check_and_create.outputs.branch-name }}
          after_pr_array: ${{ steps.after-pr-check.outputs.after_pr_exist }}

      - name: set pr num output
        id: set-after-pr-num
        run: |
          afterprnumoutput="${{ env.after_pr_number }}"
          echo "AFTERPRNUMOUTPUT=$afterprnumoutput" >> $GITHUB_OUTPUT

      - name: print PR
        run: echo ${{ steps.set-after-pr-num.outputs.AFTERPRNUMOUTPUT }}

      - name: Update Pull Request Comment
        if: steps.get_pr_num.outcome == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          script: |
            const newComment = 'New comment to append to the PR.';
            github.rest.issues.createComment({
                issue_number: ${{ steps.set-after-pr-num.outputs.AFTERPRNUMOUTPUT }},
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: newComment
            });
